name: Deploy to Conoha

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        
    - name: Deploy to Conoha
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CONOHA_HOST }}
        username: ${{ secrets.CONOHA_USERNAME }}
        key: ${{ secrets.CONOHA_SSH_KEY }}
        source: "dist/"
        target: "/var/www/html/"